######################################################################
##
## Filename: sdramTB.udo
## Created on: Fri Oct 05 1:56:40 am E. Australia Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
